### ISSUE TITLE
How about add HTTP proxy mode?

### ISSUE THREAD

**Issue by KevinZonda** [ExcitedCodes/NaiveGUI#1]
You can refer to [Proxy.cs](https://github.com/KevinZonda/trojan-client-slim/blob/TCS-3.0/TCS/Util/Proxy.cs) to set HTTP proxy.
And use Clash or Privoxy switch SOCKS5 to HTTP proxy. 
Have a good day! ☺

**Comment by ExcitedCodes** [comment]
Actually, the NaiveProxy have built-in HTTP proxy support, just use http://addr:port as the listener parameter.
The only shortage is it doesn't support dual proxy protocols on the same port, which we can overcome by setting up multiple listeners.

The original design of NaiveGUI is to setup multiple listeners corresponding to multiple remotes, and the user do the actual proxy stuff using Proxifier, which allows them to select different remote per app/host etc. 

And this brings up another question: We have multiple listeners, which one to set as the system proxy? It's hard to decide...

**Comment by KevinZonda** [comment]
Windows can only accept HTTP proxy.

**Comment by KevinZonda** [comment]
If you want to bypass some websites, SOCKS5 may be better.

```
Naive(Socks5) - Clash/Privoxy(HTTP) -> Windows Interface
```

But proxy all the transfer, just HTTP proxy.

```
Naive(HTTP) -> Windows Interface
```

**Comment by ExcitedCodes** [comment]
I can't get your point, IMO you can create listeners using http://xxxxx
![image](https://user-images.githubusercontent.com/61885669/77734839-66065700-7044-11ea-9b11-710f543ed537.png)

And configure your windows:
![image](https://user-images.githubusercontent.com/61885669/77734927-90f0ab00-7044-11ea-900c-48c61a97c223.png)

It's 100% working solution for said scenario (HTTP(S) Proxy).

**Comment by KevinZonda** [comment]
> HTTP

So why not make it automaticly?

**Comment by ExcitedCodes** [comment]
> > HTTP
> 
> So why not make it automaticly?

As I mentioned earlier, we have multiple listeners.
To do this automatically, we must create options like "Which one to set as system-wide proxy?", which increases the configuration complexity.
If you really need said function, you may implement it and create PR, I'd be appreciate to merge it.
